---
- name: Update apt-get repo and cache
  apt: 
    update_cache=yes 
    force_apt_get=yes 
    cache_valid_time=3600
- name: vim install
  apt: 
    name=vim
    state=present
- name: zip install
  apt: 
    name=zip
    state=present
